"""Add meal plan editing fields

Revision ID: 79ae293a87e9
Revises: cb870e1dfc25
Create Date: 2025-11-05 16:23:50.531878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79ae293a87e9'
down_revision: Union[str, None] = 'cb870e1dfc25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add customized column as nullable first
    op.add_column('meal_plans', sa.Column('customized', sa.Boolean(), nullable=True))
    # Set default value for existing rows
    op.execute("UPDATE meal_plans SET customized = FALSE WHERE customized IS NULL")
    # Make it non-nullable
    op.alter_column('meal_plans', 'customized', nullable=False)

    op.add_column('meal_plans', sa.Column('original_meals', sa.JSON(), nullable=True))
    op.add_column('meal_plans', sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meal_plans', 'edited_at')
    op.drop_column('meal_plans', 'original_meals')
    op.drop_column('meal_plans', 'customized')
    # ### end Alembic commands ###
