"""Add meal planning and health fields

Revision ID: eb918e58ba31
Revises: 18e84a16fd56
Create Date: 2025-11-02 14:30:43.773883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb918e58ba31'
down_revision: Union[str, None] = '18e84a16fd56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_meal_plans_id', table_name='meal_plans')
    op.drop_index('ix_meal_plans_task_id', table_name='meal_plans')
    op.drop_table('meal_plans')
    op.add_column('health_data', sa.Column('gender', sa.String(length=20), nullable=True))
    op.add_column('health_data', sa.Column('allergies', sa.JSON(), nullable=True))
    op.add_column('health_data', sa.Column('medical_conditions', sa.JSON(), nullable=True))
    op.add_column('health_data', sa.Column('meal_frequency', sa.String(length=50), nullable=True))
    op.add_column('health_data', sa.Column('cooking_skill', sa.String(length=50), nullable=True))
    op.add_column('health_data', sa.Column('time_available', sa.String(length=50), nullable=True))
    op.add_column('health_data', sa.Column('budget', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('health_data', 'budget')
    op.drop_column('health_data', 'time_available')
    op.drop_column('health_data', 'cooking_skill')
    op.drop_column('health_data', 'meal_frequency')
    op.drop_column('health_data', 'medical_conditions')
    op.drop_column('health_data', 'allergies')
    op.drop_column('health_data', 'gender')
    op.create_table('meal_plans',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=True),
    sa.Column('meals', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('dietary_preference', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('calorie_target', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='meal_plans_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='meal_plans_pkey'),
    sa.UniqueConstraint('task_id', name='meal_plans_task_id_key')
    )
    op.create_index('ix_meal_plans_task_id', 'meal_plans', ['task_id'], unique=True)
    op.create_index('ix_meal_plans_id', 'meal_plans', ['id'], unique=False)
    # ### end Alembic commands ###
